import iconMapRaw from '../data/icons.json';

// slug -> path relative to public/ (e.g. "icons/iron-ore.png"),
// generated by scrapers/icon_scraper.py
const iconMap = iconMapRaw as Record<string, string>;

// Must match the slugify() in scrapers/icon_scraper.py:
// collapse runs of non-alphanumerics into single dashes, trim edges.
function iconSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

// Legacy planner names whose wiki page (and icon) was renamed
const SLUG_ALIASES: Record<string, string> = {
  'sam-ore': 'sam',
};

function iconFor(name: string | undefined | null): string | null {
  if (!name) return null;
  const slug = iconSlug(name);
  const path = iconMap[slug] ?? iconMap[SLUG_ALIASES[slug] ?? ''];
  return path ? import.meta.env.BASE_URL + path : null;
}

// Small inline icon shown to the left of an item/machine name.
// Renders nothing when no icon was scraped; hides itself if the file 404s.
export function ItemIcon({ name, size = 18 }: { name?: string | null; size?: number }) {
  const src = iconFor(name);
  if (!src) return null;
  return (
    <img
      className="item-icon"
      src={src}
      alt=""
      width={size}
      height={size}
      loading="lazy"
      draggable={false}
      onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }}
    />
  );
}
